/* Generated By:JJTree: Do not edit this line. ASTAddSubExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAddSubExpression extends SimpleNode {
  protected String operation;

  public ASTAddSubExpression(int id) {
    super(id);
  }

  public ASTAddSubExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    // return this.operation;
    return "hardcoded+";
  }
}
/* JavaCC - OriginalChecksum=d5b39653de00a19eddbf6b5144717551 (do not edit this line) */
