/* Generated By:JJTree: Do not edit this line. ASTArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public class ASTArguments extends SimpleNode {
  protected ArrayList<String> identifiers = new ArrayList<>();

  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getInformation(String prefix) {
    StringBuilder sb = new StringBuilder();

    sb.append(prefix).append("{\n");

    sb.append(prefix).append("  identifiers: [\n");
    for (String identifier: identifiers) {
      sb.append(prefix).append("    ").append(identifier).append(",\n");
    }
    sb.append(prefix).append("  ],\n");

    sb.append(prefix).append("}");

    return sb.toString();
  }
}
/* JavaCC - OriginalChecksum=a33fcadd986cf30b09a6281ce096c96b (do not edit this line) */
