/* Generated By:JJTree: Do not edit this line. ASTArrayAccessExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccessExpression extends SimpleNode {
  public ASTArrayAccessExpression(int id) {
    super(id);
  }

  public ASTArrayAccessExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "[]";
  }
}
/* JavaCC - OriginalChecksum=dec61186312bf09145e85ad0c72a13a7 (do not edit this line) */
