/* Generated By:JJTree: Do not edit this line. ASTBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTBoolean extends SimpleNode {
  protected String value;

  public ASTBoolean(int id) {
    super(id);
  }

  public ASTBoolean(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.value;
  }
}
/*
 * JavaCC - OriginalChecksum=28aa6899b02b8fec86f4fb85440d0050 (do not edit this
 * line)
 */
