/* Generated By:JJTree: Do not edit this line. ASTClassFields.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassFields extends SimpleNode {
  public ASTClassFields(int id) {
    super(id);
  }

  public ASTClassFields(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "fields";
  }
}
/* JavaCC - OriginalChecksum=8d56eaedf19224effead83c72a0ed553 (do not edit this line) */
