/* Generated By:JJTree: Do not edit this line. ASTClassMethods.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassMethods extends SimpleNode {
  public ASTClassMethods(int id) {
    super(id);
  }

  public ASTClassMethods(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "methods";
  }
}
/* JavaCC - OriginalChecksum=c7c7aa802571c13aa6ab9b2c273c51a9 (do not edit this line) */
