/* Generated By:JJTree: Do not edit this line. ASTClassGeneralization.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassGeneralization extends SimpleNode {
  protected String name;

  public ASTClassGeneralization(int id) {
    super(id);
  }

  public ASTClassGeneralization(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "extends " + this.name;
  }

  public String getExtendedClass() {
    return this.name;
  }

  @Override
  protected void generateCodeNodeOpen(StringBuilder sb) {
    sb.append(".super ").append(this.name).append("\n\n")
      .append("; implicit constructor\n")
      .append(".method public <init>()V\n")
      .append("\taload_0\n")
      .append("\tinvokenonvirtual ").append(this.name).append("/<init>()V\n")
      .append("\treturn\n")
      .append(".end method\n\n");
  }
}
/* JavaCC - OriginalChecksum=9a0034a7e203a41a29caceec5a2cc981 (do not edit this line) */
