/* Generated By:JJTree: Do not edit this line. ASTDotExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDotExpression extends SimpleNode {
  public ASTDotExpression(int id) {
    super(id);
  }

  public ASTDotExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() { return "."; }
}
/* JavaCC - OriginalChecksum=9e551656e978f3b2ea8f9c6934c8e272 (do not edit this line) */
