/* Generated By:JJTree: Do not edit this line. ASTExpressionDot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionDot extends SimpleNode {
  protected String dot_text;

  public ASTExpressionDot(int id) {
    super(id);
  }

  public ASTExpressionDot(JMMParser p, int id) {
    super(p, id);
  }

  public String getInformation(String prefix) {
    return String.format("%s{ dot_text: %s }", prefix, dot_text);
  }
 
}
/* JavaCC - OriginalChecksum=c5be70cb2f4e9b2a92a13ebe94215a88 (do not edit this line) */
