/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "else";
  }
}
/* JavaCC - OriginalChecksum=ba4b481c9ed86027631c5d8ac156aa36 (do not edit this line) */
