/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIntegerLiteral extends SimpleNode implements Typed {
  protected String value;
  private static final VariableType type = new VariableType("int");

  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.value;
  }

  @Override
  public VariableType getType() {
    return type;
  }

  public String getValue() {
    return this.value;
  }

  @Override
  protected void calculateStackImpact() {
    MethodStackSizeScopes.getInstance().getMethodScope(this.scope_identifier).impactStack(1);
  }

  public static String integerValueToLoad(String value_string) {
    // put value in stack
    final int value = Integer.parseInt(value_string);
    if (value < 6) {
      return "\ticonst_" + value + "\n";
    } else if (value < 128) {
      return "\tbipush " + value + "\n";
    } else if (value < 32768) {
      return "\tsipush " + value + "\n";
    } else {
      return "\tldc " + value + "\n";
    }
  }

  @Override
  protected void generateCodeNodeClose(StringBuilder sb) {
    Node parent = this.jjtGetParent();

    if (parent != null && parent instanceof ASTAssignmentStatement && ((ASTAssignmentStatement) parent).isSupressed()) {
      // If the assignment was supressed then this literal does not need to be pushed to the stack either
      return;
    }

    sb.append(ASTIntegerLiteral.integerValueToLoad(this.value));
  }
}
/*
 * JavaCC - OriginalChecksum=4a43e323f6d0e970615023842b59d2d8 (do not edit this
 * line)
 */
