/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIdentifier extends SimpleNode implements Typed {
  protected String value;
  private Variable variable;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.value;
  }

  public Variable getVariable() {
    return variable;
  }

  @Override
  public VariableType getType() {
    return variable.getType();
  }

  @Override
  protected void applySemanticAnalysis() throws SemanticError {    
    Variable v = SymbolTableScopes.getInstance().isDeclared(this.scope_identifier, this.value);
    Node parent = this.jjtGetParent();
    if (v == null) {
      if (parent != null && parent instanceof ASTDotExpression) {
        this.variable = new Variable(new VariableType(VariableType.ignored_type, this.value), new VariableIdentifier(""));
        return;
      }
      throw new SemanticError(this.line, String.format("Using undeclared variable '%s'.", this.value));
    }

    this.variable = v;

    if (parent != null && parent instanceof ASTAssignmentStatement) {
      return;
    }

    if (!v.isInitialized()) {
      throw new SemanticError(this.line, String.format("Using variable '%s' before initialization.", this.value));
    }
  }
}
/*
 * JavaCC - OriginalChecksum=534021caa2c544cea987828b4185652b (do not edit this
 * line)
 */
