/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTIntegerLiteral extends SimpleNode implements Typed{
  protected String value;
  private static final VariableType type = new VariableType("int");

  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.value;
  }

  @Override
  public VariableType getType() {
    return type;
  }

  @Override
  protected void generateCodeNodeClose(StringBuilder sb) {
    // put value in stack
    sb.append("\tldc ").append(this.value).append("\n");
  }
}
/*
 * JavaCC - OriginalChecksum=4a43e323f6d0e970615023842b59d2d8 (do not edit this
 * line)
 */
