/* Generated By:JJTree: Do not edit this line. ASTIfBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfBody extends SimpleNode {
  public ASTIfBody(int id) {
    super(id);
  }

  public ASTIfBody(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "ifBody";
  }
}
/* JavaCC - OriginalChecksum=2866cf9750a7fe8840e615ea20dba0c8 (do not edit this line) */
