/* Generated By:JJTree: Do not edit this line. ASTLessThanExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThanExpression extends SimpleNode {
  public ASTLessThanExpression(int id) {
    super(id);
  }

  public ASTLessThanExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() { return "<"; }
}
/* JavaCC - OriginalChecksum=9405f26bbe0b95a12e7d396311b1838b (do not edit this line) */
