/* Generated By:JJTree: Do not edit this line. ASTLessThanExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThanExpression extends SimpleNode implements Typed {
  private VariableType type;

  public ASTLessThanExpression(int id) {
    super(id);
  }

  public ASTLessThanExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "<";
  }

  @Override
  public VariableType getType() {
    return type;
  }

  @Override
  protected void applySemanticAnalysis() throws SemanticError {
    VariableType lhs = ((Typed) children[0]).getType();
    VariableType rhs = ((Typed) children[1]).getType();
    if (!((lhs.isInt() || lhs.isIgnored()) && (rhs.isInt() || rhs.isIgnored()))) {
      throw new SemanticError(this.line, String.format("Invalid operand types %s and %s for operator <", lhs, rhs));
    }

    // Calculate own type
    this.type = new VariableType("boolean");
  }
}
/* JavaCC - OriginalChecksum=9405f26bbe0b95a12e7d396311b1838b (do not edit this line) */
