/* Generated By:JJTree: Do not edit this line. ASTLength.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLength extends SimpleNode {
  public ASTLength(int id) {
    super(id);
  }

  public ASTLength(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "length";
  }

  @Override
  protected void calculateStackImpact() {
    MethodStackSizeScopes.getInstance().getMethodScope(this.scope_identifier).impactStack(0);
  }

  @Override
  protected void generateCodeNodeClose(StringBuilder sb) {
    sb.append("\tarraylength\n");
  }
}
/* JavaCC - OriginalChecksum=cc3807a3049325177fbdf3a127e5e774 (do not edit this line) */
