/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends NodeWithSymbolTable implements DeclarationNode {
  public ASTMainDeclaration(int id) {
    super(id);
    // So that it can be used in the superclass
    this.name = "main";
  }

  public ASTMainDeclaration(JMMParser p, int id) {
    super(p, id);
    // So that it can be used in the superclass
    this.name = "main";
  }

  @Override
  public String getNodeName() {
    return "declaration: main()";
  }

  @Override
  public String getIdentifier() {
    return "main";
  }

  @Override
  public String getType() {
    return "function";
  }
}
/* JavaCC - OriginalChecksum=8a4e52ddec71c519a361c616e3c2c9f6 (do not edit this line) */
