/* Generated By:JJTree: Do not edit this line. ASTMethodParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodParameter extends SimpleNode {
  protected String name;

  public ASTMethodParameter(int id) {
    super(id);
  }

  public ASTMethodParameter(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.name;
  }
}
/* JavaCC - OriginalChecksum=abccf57d3baa30c30d2466acbaa6d5db (do not edit this line) */
