import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMainDeclaration extends MethodDeclarationNode {
  protected String arg_name;

  public ASTMainDeclaration(int id) {
    super(id);
    // So that it can be used in the superclass
    this.name = "main";
    // The return value and identifier of main is always the same
    this.ret = new VariableType("void");
    this.identifier = new VariableIdentifier(this.name);
  }

  public ASTMainDeclaration(JMMParser p, int id) {
    super(p, id);
    // So that it can be used in the superclass
    this.name = "main";
    // The return value of main is always the same
    this.ret = new VariableType("void");
    this.identifier = new VariableIdentifier(this.name);
  }

  @Override
  protected void buildSymbolTable() {
    // Register method parameters because they are local reference
    for (Variable param : params) {
      this.registerInSymbolTable(param);
      param.markAsInitialized();  // main parameters are assumed to be initialized
      param.markAsParameter(); // Marking the parameter variables as parameters, useful for code generation
    }

    // First children are directly var declarations because the rest is always the same (return and args)
    for (int i = 0; i < children.length; ++i) {
      if (children[i] instanceof DeclarationNode) {
        this.registerInSymbolTable(children[i]);
      } else {
        // The declarations are all sequential in the start of the method code
        break;
      }
    }

    SymbolTableScopes.getInstance().addMethodScope(this.getScopeIdentifier(), this.line, this.symbol_table);
  }

  @Override
  public void prepareInternalInfo() {
    this.params = new Variable[] {new Variable(new VariableType("String[]"), new VariableIdentifier(this.arg_name))};
  }

  @Override
  protected void generateCodeNodeOpen(StringBuilder sb) {
    sb.append(".method public static main([Ljava/lang/String;)V\n");
    
    // TODO: Fix code duplication between this and MethodDeclaration
    
    // Temporary placeholder
    sb.append("\t.limit stack 10 ; temporary while stack size is not being calculated\n");
    // Number of local variables = number of entries in the symbol table + 1
    sb.append(String.format("\t.limit locals %d\n", this.calcLocalsLimit() + 1));

    // Creating the local variables (done here because of the sequential indexes)

    // The starting index is the number of parameters (+1 because of 'this')
    int locals_start_idx = ((int) this.symbol_table.values().stream().filter(Variable::isParameter).count()) + 1;
    List<Variable> local_variables = this.symbol_table.values().stream().filter(Predicate.not(Variable::isParameter)).collect(Collectors.toList());

    for (Variable local_var : local_variables) {
      local_var.setLocalVarIndex(locals_start_idx);
      sb.append(String.format(local_var.toJasminDeclaration(), locals_start_idx++));
    }
  }

  @Override
  protected void generateCodeNodeClose(StringBuilder sb) {
    sb.append("\treturn\n")
      .append(".end method\n\n");
  }
}
/* JavaCC - OriginalChecksum=8a4e52ddec71c519a361c616e3c2c9f6 (do not edit this line) */
