/* Generated By:JJTree: Do not edit this line. ASTMethodParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodParameters extends SimpleNode {
  public ASTMethodParameters(int id) {
    super(id);
  }

  public ASTMethodParameters(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "Parameters";
  }
}
/* JavaCC - OriginalChecksum=8dbcb47ea87ae8837aa83240482935f5 (do not edit this line) */
