/* Generated By:JJTree: Do not edit this line. ASTNotExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNotExpression extends SimpleNode {
  public ASTNotExpression(int id) {
    super(id);
  }

  public ASTNotExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "!";
  }
}
/* JavaCC - OriginalChecksum=e213793f1ee47cd5b95e1a006bfe6712 (do not edit this line) */
