/* Generated By:JJTree: Do not edit this line. ASTNewExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewExpression extends SimpleNode {
  public ASTNewExpression(int id) {
    super(id);
  }

  public ASTNewExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "new";
  }
}
/* JavaCC - OriginalChecksum=1c5d1c8675be9c00e49865921bb77fe8 (do not edit this line) */
