/* Generated By:JJTree: Do not edit this line. ASTNotExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNotExpression extends SimpleNode implements Typed {
  private VariableType type;

  public ASTNotExpression(int id) {
    super(id);
  }

  public ASTNotExpression(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "!";
  }

  @Override
  public VariableType getType() {
    return type;
  }

  @Override
  protected void applySemanticAnalysis() throws SemanticError {
    VariableType operand = ((Typed) children[0]).getType();

    if (!((operand.isBoolean() || operand.isIgnored()))) {
      throw new SemanticError(this.line, String.format("Invalid operand type %s for operator !", operand));
    }

    // Calculate own type
    this.type = new VariableType("boolean");
  }

  @Override
  protected void calculateStackImpact() {
    // Might raise the maximum so must be done like this
    MethodStackSizeScopes.getInstance().getMethodScope(this.scope_identifier).impactStack(1);
    MethodStackSizeScopes.getInstance().getMethodScope(this.scope_identifier).impactStack(-1);
  }

  @Override
  protected void generateCodeNodeClose(StringBuilder sb) {
    sb.append("\ticonst_1\n\tixor\n");
  }
}
/* JavaCC - OriginalChecksum=e213793f1ee47cd5b95e1a006bfe6712 (do not edit this line) */
