/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "return";
  }
}
/* JavaCC - OriginalChecksum=9b3082da7d18bccf67b467d02cd5241c (do not edit this line) */
