/* Generated By:JJTree: Do not edit this line. ASTrecover_while_error.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrecover_while_error extends SimpleNode {
  public ASTrecover_while_error(int id) {
    super(id);
  }

  public ASTrecover_while_error(JMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd06f8895bc081b2cce0ff99f04507bf (do not edit this line) */
