/* Generated By:JJTree: Do not edit this line. ASTSimpleExpressionTerminal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimpleExpressionTerminal extends SimpleNode {
  protected String value;

  public ASTSimpleExpressionTerminal(int id) {
    super(id);
  }

  public ASTSimpleExpressionTerminal(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return this.value;
  }
}
/* JavaCC - OriginalChecksum=74e75927eb5fd412c7cb3fb0700966a0 (do not edit this line) */
