/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTVarDeclaration extends SimpleNode implements DeclarationNode {
  protected String identifier;

  private ASTType type;

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "declaration: " + this.identifier;
  }

  @Override
  public String getIdentifier() {
    return this.identifier;
  }

  @Override
  public String getType() {
    return this.type.getNodeName();
  }

  @Override
  public String getInformation() {
    return String.format("%s::%s", this.getIdentifier(), this.getType());
  }

  @Override
  public void prepareInternalInfo() {
    this.type = ((ASTType) children[0]);
  }
}
/*
 * JavaCC - OriginalChecksum=2fe954f88636d4a225fdb6d7f6dd1974 (do not edit this
 * line)
 */

        