/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTVarDeclaration extends SimpleNode {
  protected ASTType type;
  protected String identifier;

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getInformation(String prefix) {
    StringBuilder sb = new StringBuilder();

    sb.append(prefix).append("{\n");
    sb.append(prefix).append("  type: ").append(type.getInformation("")).append(",\n");
    sb.append(prefix).append("  identifier: ").append(identifier).append(",\n");
    sb.append(prefix).append("}");

    return sb.toString();
  }

}
/*
 * JavaCC - OriginalChecksum=2fe954f88636d4a225fdb6d7f6dd1974 (do not edit this
 * line)
 */

        