/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "while";
  }

  @Override
  protected void applySemanticAnalysis() throws SemanticError {
    Node lhs_raw = children[0];
    
    VariableType lhs = ((Typed) lhs_raw).getType();

    if (!(lhs.isBoolean() || lhs.isIgnored())) {
      throw new SemanticError(this.line, String.format("Invalid type '%s' in If statement (boolean was expected)", lhs));
    }
  }
}
/* JavaCC - OriginalChecksum=bc101b754e6ad81cd1d346b016d5ce12 (do not edit this line) */
