/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(JMMParser p, int id) {
    super(p, id);
  }

  @Override
  public String getNodeName() {
    return "body";
  }
}
/* JavaCC - OriginalChecksum=a372a0b2f522b0fb66f679bbe3a0d54e (do not edit this line) */
