/* Generated By:JavaCC: Do not edit this line. JMMParserTreeConstants.java Version 5.0 */
public interface JMMParserTreeConstants
{
  public int JJTRECOVER_WHILE_ERROR = 0;
  public int JJTPROGRAM = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTCLASSGENERALIZATION = 4;
  public int JJTVOID = 5;
  public int JJTCLASSFIELDS = 6;
  public int JJTCLASSMETHODS = 7;
  public int JJTTYPE = 8;
  public int JJTMAINDECLARATION = 9;
  public int JJTMETHODDECLARATION = 10;
  public int JJTRETURN = 11;
  public int JJTMETHODPARAMETERS = 12;
  public int JJTMETHODPARAMETER = 13;
  public int JJTIFSTATEMENT = 14;
  public int JJTIFBODY = 15;
  public int JJTELSEBODY = 16;
  public int JJTWHILESTATEMENT = 17;
  public int JJTWHILEBODY = 18;
  public int JJTASSIGNMENTSTATEMENT = 19;
  public int JJTANDEXPRESSION = 20;
  public int JJTLESSTHANEXPRESSION = 21;
  public int JJTARITHMETICEXPRESSION = 22;
  public int JJTNOTEXPRESSION = 23;
  public int JJTARRAYACCESSEXPRESSION = 24;
  public int JJTDOTEXPRESSION = 25;
  public int JJTLENGTH = 26;
  public int JJTMETHODCALL = 27;
  public int JJTSIMPLEEXPRESSIONTERMINAL = 28;
  public int JJTNEWEXPRESSION = 29;


  public String[] jjtNodeName = {
    "recover_while_error",
    "Program",
    "VarDeclaration",
    "ClassDeclaration",
    "ClassGeneralization",
    "void",
    "ClassFields",
    "ClassMethods",
    "Type",
    "MainDeclaration",
    "MethodDeclaration",
    "Return",
    "MethodParameters",
    "MethodParameter",
    "IfStatement",
    "IfBody",
    "ElseBody",
    "WhileStatement",
    "WhileBody",
    "AssignmentStatement",
    "AndExpression",
    "LessThanExpression",
    "ArithmeticExpression",
    "NotExpression",
    "ArrayAccessExpression",
    "DotExpression",
    "Length",
    "MethodCall",
    "SimpleExpressionTerminal",
    "NewExpression",
  };
}
/* JavaCC - OriginalChecksum=df0a37c492a93a5d16fe188a3b079cda (do not edit this line) */
